[package]
name = "cps"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "cps"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.56", features = ["derive"] }
colored = "3.1.1"
rand = "0.9.2"
